### PR TITLE
MAP2 working + tested with stretched JPEG2000 image

### PR DESCRIPTION
**Pull request by AustinSanders**
~~EDIT --- DO NOT MERGE~~

It looks like the actual JPEG2000 image was not created.  Output was recorded in the '/scratch/pds_services/service_refactor/MAP_stretch.out' and no errors were recorded in '/scratch/pds_services/service_refactor/MAP_stretch.err'.

Job Key (stretched JPEG2000): 7ca0cd0e4ae495124b2526e7c620271a

### CODE REVIEW

**Comment by dpmayerUSGS** [comment]
@AustinSanders If this shouldn't be merged, I'd rather close it and have you submit another PR when it's ready.

**Comment by AustinSanders** [comment]
After further testing, all files in this PR are up to date and functioning properly.  The bugs associated with the JP2 creation were in unrelated files (xml2redis) that are not intended for merge into production branches.

Keys used for testing:
e2c265b7446c7db61b167cb88d70ba3c   (stretched jp2 image)
0faf2b47c6c2839c1ee49cdbb62fe4d7 (unstretched geotiff)

The output can be found in /scratch/pds_services/<key>

Note that the aux and mask files for the jp2 image are still in the directory -- we may want to automatically delete those.

**Comment by thareUSGS** [comment]
> Note that the aux and mask files for the jp2 image are still in the directory -- we may want to automatically delete those.

I recommend we keep them. The *.aux files can be valuable. The masks files, which are a newer "feature" for GDAL, may help to maintain NoData areas for lossly formats. Support for them is probably only in GDAL, but as many applications use GDAL support should grow.

**Comment by dpmayerUSGS** [comment]
As per conversation with @AustinSanders last week, going to close this again in anticipation of a new PR directly into `master`

**Pull request closed without merging**
